_wandb:
    value:
        cli_version: 0.23.0
        e:
            7hck8sr9cgx1lflow9ujou3uf80twzkl:
                apple:
                    ecpuCores: 4
                    gpuCores: 20
                    memoryGb: 24
                    name: Apple M4 Pro
                    pcpuCores: 10
                    ramTotalBytes: "25769803776"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 14
                cpu_count_logical: 14
                disk:
                    /:
                        total: "494384795648"
                        used: "260034523136"
                email: lucky0110111@gmail.com
                executable: /opt/homebrew/Caskroom/miniconda/base/envs/inthon/bin/python3
                git:
                    commit: 8a1b470f9f5f693df13c76ae9602eb9264306d2d
                    remote: https://github.com/pizzazoa/inthon-dataton.git
                host: jeongtaehuiui-MacBookPro.local
                memory:
                    total: "25769803776"
                os: macOS-15.6.1-arm64-arm-64bit
                program: /Users/taeheejeong/Desktop/inthon-dataton/train.py
                python: CPython 3.10.19
                root: /Users/taeheejeong/Desktop/inthon-dataton
                startedAt: "2025-11-15T06:44:34.146931Z"
                writerId: 7hck8sr9cgx1lflow9ujou3uf80twzkl
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 13
                - 16
                - 61
            "4": 3.10.19
            "5": 0.23.0
            "12": 0.23.0
            "13": darwin-arm64
d_model:
    value: 256
dim_ff:
    value: 1024
dropout:
    value: 0.1
lr:
    value: 0.0005
max_gen_len:
    value: 30
max_train_steps:
    value: 20000
n_dec_layers:
    value: 4
n_enc_layers:
    value: 4
n_head:
    value: 8
num_epochs:
    value: 100
save_best_path:
    value: best_model.pt
show_valid_samples:
    value: 5
valid_every:
    value: 500
